const phylogeny = {
  nodes: [

    // ── Domains ───────────────────────────────────────────────────────────────
    { id: "root",             parent: null,               age_mya: 3800,
      label: "life",                     sci: "LUCA",  wiki: "Last_universal_common_ancestor" },
    { id: "bacteria",         parent: "root",             age_mya: 3500,
      label: "bacteria",                 sci: "Bacteria" },
    // Under the two-domain model, eukaryotes evolved from within Archaea (the Asgard lineage),
    // so "Archaea" is a grade (paraphyletic).  The monophyletic Archaea clade includes eukaryotes.
    { id: "archaea",          parent: "root",             age_mya: 3500,
      label: "archaea",                  sci: "Archaea" },
    // Euryarchaeota: deep-branching archaeal lineage (methanogen's phylum); most distantly related to eukaryotes
    { id: "euryarchaeota",    parent: "archaea",          age_mya: 3400,
      label: "euryarchaeotes",           sci: "Euryarchaeota" },
    // Asgard archaea + eukaryotes: the clade within which eukaryotes are nested
    { id: "asgard_eukarya",   parent: "archaea",          age_mya: 2600,
      label: "Asgard archaea and eukaryotes", sci: "Asgardarchaeota + Eukaryota", wiki: "Asgard_archaea" },
    { id: "eukarya",          parent: "asgard_eukarya",   age_mya: 2100,
      label: "eukaryotes",               sci: "Eukaryota" },

    // ── Major eukaryote lineages ───────────────────────────────────────────────
    // Amorphea (= Unikonta): opisthokonts + amoebozoans — sister to Diaphoretickes
    { id: "amorphea",         parent: "eukarya",          age_mya: 1800,
      label: "amorpheans",               sci: "Amorphea" },
    // Diaphoretickes (= Bikonta): SAR + Archaeplastida
    { id: "diaphoretickes",   parent: "eukarya",          age_mya: 1500,
      label: "diaphoretickes",           sci: "Diaphoretickes" },
    // SAR supergroup: Stramenopiles + Alveolates + Rhizaria
    { id: "sar",              parent: "diaphoretickes",   age_mya: 1100,
      label: "SAR supergroup",           sci: "SAR",   wiki: "SAR_supergroup" },
    { id: "stramenopila",     parent: "sar",              age_mya: 1000,
      label: "stramenopiles",            sci: "Stramenopila" },
    { id: "alveolata",        parent: "sar",              age_mya: 1000,
      label: "alveolates",               sci: "Alveolata" },
    // Archaeplastida: red algae + green algae + land plants
    { id: "archaeplastida",   parent: "diaphoretickes",   age_mya: 1200,
      label: "archaeplastids",           sci: "Archaeplastida" },
    { id: "opisthokonta",     parent: "amorphea",         age_mya: 1525,
      label: "opisthokonts",             sci: "Opisthokonta" },
    { id: "plants_clade",     parent: "archaeplastida",   age_mya: 475,
      label: "land plants",              sci: "Embryophyta" },

    // ── Fungi ─────────────────────────────────────────────────────────────────
    { id: "fungi",            parent: "opisthokonta",     age_mya: 1000,
      label: "fungi",                    sci: "Fungi" },
    { id: "ascomycota",       parent: "fungi",            age_mya: 600,
      label: "sac fungi",                sci: "Ascomycota" },
    { id: "basidiomycota",    parent: "fungi",            age_mya: 600,
      label: "club fungi",               sci: "Basidiomycota" },

    // ── Animals: basal ────────────────────────────────────────────────────────
    { id: "animalia",         parent: "opisthokonta",     age_mya: 800,
      label: "animals",                  sci: "Animalia" },
    { id: "porifera",         parent: "animalia",         age_mya: 700,
      label: "sponges",                  sci: "Porifera" },
    { id: "eumetazoa",        parent: "animalia",         age_mya: 650,
      label: "eumetazoans",              sci: "Eumetazoa" },
    { id: "cnidaria",         parent: "eumetazoa",        age_mya: 600,
      label: "cnidarians",               sci: "Cnidaria" },
    { id: "bilateria",        parent: "eumetazoa",        age_mya: 555,
      label: "bilaterians",              sci: "Bilateria" },

    // ── Protostomes ───────────────────────────────────────────────────────────
    { id: "protostomia",      parent: "bilateria",        age_mya: 550,
      label: "protostomes",              sci: "Protostomia" },
    { id: "ecdysozoa",        parent: "protostomia",      age_mya: 540,
      label: "ecdysozoans",              sci: "Ecdysozoa" },
    { id: "lophotrochozoa",   parent: "protostomia",      age_mya: 530,
      label: "lophotrochozoans",         sci: "Lophotrochozoa" },
    { id: "arthropoda",       parent: "ecdysozoa",        age_mya: 520,
      label: "arthropods",               sci: "Arthropoda" },
    { id: "chelicerata",      parent: "arthropoda",       age_mya: 480,
      label: "chelicerates",             sci: "Chelicerata" },
    { id: "arachnida",        parent: "chelicerata",      age_mya: 430,
      label: "arachnids",                sci: "Arachnida" },
    { id: "mandibulata",      parent: "arthropoda",       age_mya: 480,
      label: "mandibulates",             sci: "Mandibulata" },
    { id: "crustacea",        parent: "mandibulata",      age_mya: 450,
      label: "crustaceans",              sci: "Crustacea" },
    { id: "insecta",          parent: "mandibulata",      age_mya: 400,
      label: "insects",                  sci: "Insecta" },
    { id: "holometabola",     parent: "insecta",          age_mya: 300,
      label: "holometabolans",           sci: "Holometabola" },
    { id: "mollusca",         parent: "lophotrochozoa",   age_mya: 530,
      label: "molluscs",                 sci: "Mollusca" },
    { id: "annelida",         parent: "lophotrochozoa",   age_mya: 530,
      label: "annelids",                 sci: "Annelida" },

    // ── Deuterostomes ─────────────────────────────────────────────────────────
    { id: "deuterostomia",    parent: "bilateria",        age_mya: 550,
      label: "deuterostomes",            sci: "Deuterostomia" },
    { id: "echinodermata",    parent: "deuterostomia",    age_mya: 520,
      label: "echinoderms",              sci: "Echinodermata" },
    { id: "chordata",         parent: "deuterostomia",    age_mya: 520,
      label: "chordates",                sci: "Chordata" },
    { id: "tunicata",         parent: "chordata",         age_mya: 520,
      label: "tunicates",                sci: "Tunicata" },
    { id: "vertebrata",       parent: "chordata",         age_mya: 480,
      label: "vertebrates",              sci: "Vertebrata" },
    { id: "chondrichthyes",   parent: "vertebrata",       age_mya: 450,
      label: "cartilaginous fishes",     sci: "Chondrichthyes" },
    { id: "osteichthyes",     parent: "vertebrata",       age_mya: 450,
      label: "bony vertebrates",         sci: "Osteichthyes" },
    { id: "actinopterygii",   parent: "osteichthyes",     age_mya: 430,
      label: "ray-finned fishes",        sci: "Actinopterygii" },
    { id: "sarcopterygii",    parent: "osteichthyes",     age_mya: 430,
      label: "lobe-finned fishes",       sci: "Sarcopterygii" },
    // Rhipidistia: lungfishes + tetrapods (sister to coelacanths within Sarcopterygii)
    { id: "rhipidistia",      parent: "sarcopterygii",    age_mya: 415,
      label: "rhipidistians",            sci: "Rhipidistia" },
    { id: "tetrapoda",        parent: "rhipidistia",      age_mya: 375,
      label: "tetrapods",                sci: "Tetrapoda" },
    { id: "amphibia_clade",   parent: "tetrapoda",        age_mya: 360,
      label: "amphibians",               sci: "Amphibia" },
    { id: "amniota",          parent: "tetrapoda",        age_mya: 320,
      label: "amniotes",                 sci: "Amniota",
      hint: "basically mammals and reptiles"},

    // ── Reptiles, birds & dinosaurs ───────────────────────────────────────────
    { id: "sauropsida",       parent: "amniota",          age_mya: 310,
      label: "reptiles and birds",       sci: "Sauropsida" },
    { id: "lepidosauria",     parent: "sauropsida",       age_mya: 280,
      label: "lepidosaurs",              sci: "Lepidosauria" },
    // Archelosauria: turtles + archosaurs (molecular consensus; turtles nest within diapsids)
    { id: "archelosauria",    parent: "sauropsida",       age_mya: 255,
      label: "archelosaurs",             sci: "Archelosauria" },
    { id: "archosauria",      parent: "archelosauria",    age_mya: 245,
      label: "archosaurs",               sci: "Archosauria" },
    { id: "crocodilia",       parent: "archosauria",      age_mya: 95,
      label: "crocodilians",             sci: "Crocodilia" },
    // Ornithodira: pterosaurs + dinosaurs (including all modern birds)
    { id: "ornithodira",      parent: "archosauria",      age_mya: 240,
      label: "ornithodirans",            sci: "Ornithodira" },
    // Dinosauria includes birds; Saurischia (theropods) contains T. rex and Aves as sister groups
    { id: "dinosauria",       parent: "ornithodira",      age_mya: 235,
      label: "dinosaurs",                sci: "Dinosauria" },
    { id: "saurischia",       parent: "dinosauria",       age_mya: 230,
      label: "saurischians",             sci: "Saurischia" },
    { id: "aves",             parent: "saurischia",       age_mya: 95,
      label: "birds",                    sci: "Aves" },
    // Inopinaves: pigeons + eagles + many others; Australaves: falcons + parrots
    { id: "inopinaves",       parent: "aves",             age_mya: 70,
      label: "inopinaves",               sci: "Inopinaves" },
    { id: "australaves",      parent: "aves",             age_mya: 70,
      label: "australaves",              sci: "Australaves" },

    // ── Mammals ───────────────────────────────────────────────────────────────
    { id: "mammalia",         parent: "amniota",          age_mya: 310,
      label: "mammals",                  sci: "Mammalia" },
    { id: "monotremata",      parent: "mammalia",         age_mya: 180,
      label: "monotremes",               sci: "Monotremata" },
    { id: "theria",           parent: "mammalia",         age_mya: 180,
      label: "therians",                 sci: "Theria" },
    { id: "marsupialia",      parent: "theria",           age_mya: 80,
      label: "marsupials",               sci: "Marsupialia" },
    { id: "placentalia",      parent: "theria",           age_mya: 105,
      label: "placental mammals",        sci: "Placentalia" },
    // Atlantogenata: Xenarthra + Afrotheria; Boreoeutheria: Laurasiatheria + Euarchontoglires
    { id: "atlantogenata",    parent: "placentalia",      age_mya: 90,
      label: "atlantogenatans",          sci: "Atlantogenata" },
    { id: "boreoeutheria",    parent: "placentalia",      age_mya: 90,
      label: "boreoutherians",           sci: "Boreoeutheria" },
    { id: "xenarthra",        parent: "atlantogenata",    age_mya: 90,
      label: "xenarthrans",              sci: "Xenarthra" },
    { id: "afrotheria",       parent: "atlantogenata",    age_mya: 90,
      label: "afrotherians",             sci: "Afrotheria" },
    { id: "proboscidea",      parent: "afrotheria",       age_mya: 65,
      label: "elephants",                sci: "Proboscidea" },
    { id: "laurasiatheria",   parent: "boreoeutheria",    age_mya: 90,
      label: "laurasiatherians",         sci: "Laurasiatheria" },
    { id: "euarchontoglires", parent: "boreoeutheria",    age_mya: 90,
      label: "euarchontoglirans",        sci: "Euarchontoglires" },
    // Ferae: carnivorans + pangolins
    { id: "ferae",            parent: "laurasiatheria",   age_mya: 85,
      label: "ferae",                    sci: "Ferae" },
    { id: "carnivora",        parent: "ferae",            age_mya: 42,
      label: "carnivorans",              sci: "Carnivora" },
    { id: "feliformia",       parent: "carnivora",        age_mya: 40,
      label: "cat-like carnivorans",     sci: "Feliformia" },
    { id: "hyaenidae",        parent: "feliformia",       age_mya: 15,
      label: "hyenas and aardwolves",    sci: "Hyaenidae" },
    { id: "caniformia",       parent: "carnivora",        age_mya: 40,
      label: "dog-like carnivorans",     sci: "Caniformia" },
    { id: "canidae",          parent: "caniformia",       age_mya: 12,
      label: "canids",                   sci: "Canidae" },
    // Arctoidea: bears (incl. giant panda) + pinnipeds (seals etc.) within Caniformia
    { id: "arctoidea",        parent: "caniformia",       age_mya: 38,
      label: "arctoids",                 sci: "Arctoidea" },
    // Cetartiodactyla: even-toed ungulates + whales
    { id: "cetartiodactyla",  parent: "laurasiatheria",   age_mya: 60,
      label: "even-toed ungulates and whales", sci: "Cetartiodactyla" },
    // Whippomorpha: hippos + cetaceans (closest relatives)
    { id: "whippomorpha",     parent: "cetartiodactyla",  age_mya: 55,
      label: "whippomorphs",             sci: "Whippomorpha" },
    { id: "cetacea",          parent: "whippomorpha",     age_mya: 50,
      label: "whales and dolphins",      sci: "Cetacea" },
    { id: "ruminantia",       parent: "cetartiodactyla",  age_mya: 50,
      label: "ruminants",                sci: "Ruminantia" },
    { id: "primates",         parent: "euarchontoglires", age_mya: 85,
      label: "primates",                 sci: "Primates" },
    // Glires: rodents + lagomorphs
    { id: "glires",           parent: "euarchontoglires", age_mya: 80,
      label: "glires",                   sci: "Glires" },
    { id: "rodentia",         parent: "glires",           age_mya: 75,
      label: "rodents",                  sci: "Rodentia" },
    // Muridae: Old World mice and rats (mouse + rat); sister to cricetids (hamster) within Rodentia
    { id: "muridae",          parent: "rodentia",         age_mya: 30,
      label: "Old World mice and rats",  sci: "Muridae" },
    { id: "hominidae",        parent: "primates",         age_mya: 15,
      label: "great apes",               sci: "Hominidae" },

    // ── Plants ────────────────────────────────────────────────────────────────
    { id: "bryophyta",        parent: "plants_clade",     age_mya: 470,
      label: "bryophytes",               sci: "Bryophyta" },
    { id: "tracheophyta",     parent: "plants_clade",     age_mya: 430,
      label: "vascular plants",          sci: "Tracheophyta" },
    { id: "gymnospermae",     parent: "tracheophyta",     age_mya: 310,
      label: "gymnosperms",              sci: "Gymnospermae" },
    { id: "angiosperms",      parent: "tracheophyta",     age_mya: 160,
      label: "flowering plants",         sci: "Angiospermae" },
    // Water lilies (Nymphaeales) are basal angiosperms, sister to core angiosperms
    { id: "core_angiosperms", parent: "angiosperms",      age_mya: 140,
      label: "core angiosperms",         sci: "Mesangiospermae" },
    { id: "monocots",         parent: "core_angiosperms", age_mya: 140,
      label: "monocots",                 sci: "Monocotyledoneae" },
    { id: "eudicots",         parent: "core_angiosperms", age_mya: 125,
      label: "eudicots",                 sci: "Eudicotyledoneae" },

    // ── Leaf organisms ────────────────────────────────────────────────────────
    // tier 1–9 unlock system (tier 1 = available from start, unlocked via XP above that)

    // Prokaryotes
    { id: "ecoli",       parent: "bacteria",         age_mya: 0, isLeaf: true, tier: 5,
      commonName: "E. coli",              sci: "Escherichia coli",
      funFact: "One of the most studied organisms on Earth, yet most strains are harmless gut residents.",
      image: "e-coli", emoji: "🦠" },
    { id: "cyanobacteria", parent: "bacteria",       age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Cyanobacteria",        sci: "Anabaena sp.", wiki: "Cyanobacteria",
      funFact: "Evolved oxygenic photosynthesis over 2.7 billion years ago, gradually saturating the atmosphere with oxygen — a transformation so radical it is called the Great Oxidation Event.",
      image: "cyanobacteria", emoji: "🌿" },
    { id: "methanogen",  parent: "euryarchaeota",    age_mya: 0, isLeaf: true, tier: 7,
      commonName: "Methanogen",           sci: "Methanocaldococcus jannaschii",
      funFact: "Produces methane as a metabolic byproduct; found in deep-sea hydrothermal vents at 85 °C.",
      image: "methanogen", emoji: "♨️" },

    // Protists
    { id: "kelp",        parent: "stramenopila",     age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Giant kelp",           sci: "Macrocystis pyrifera",
      funFact: "Grows up to 60 cm per day and forms underwater forests that shelter thousands of species.",
      image: "giant-kelp", emoji: "🌊" },
    { id: "plasmodium",  parent: "alveolata",        age_mya: 0, isLeaf: true, tier: 7,
      commonName: "Malaria parasite",     sci: "Plasmodium falciparum",
      funFact: "Responsible for the deadliest infectious disease in human history.",
      image: "malaria", emoji: "🦟" },

    // Fungi
    { id: "yeast",       parent: "ascomycota",       age_mya: 0, isLeaf: true, tier: 6,
      commonName: "Baker's yeast",        sci: "Saccharomyces cerevisiae",
      funFact: "Has been fermenting bread and beer for at least 9,000 years, yet shares ~23% of genes with humans.",
      image: "bakers-yeast", emoji: "🍞" },
    { id: "moldneurospora", parent: "ascomycota",    age_mya: 0, isLeaf: true, tier: 8,
      commonName: "Bread mold",           sci: "Neurospora crassa",
      funFact: "Showed that one gene makes one enzyme — a foundational experiment of molecular biology.",
      image: "bread-mold", emoji: "🍞" },
    { id: "mushroom",    parent: "basidiomycota",    age_mya: 0, isLeaf: true, tier: 5,
      commonName: "Button mushroom",      sci: "Agaricus bisporus",
      funFact: "White button, cremini, and portobello are all the same species: white is an albino strain, while cremini and portobello are the same brown strain at young and mature ages.",
      image: "button-mushroom", emoji: "🍄" },

    // Plants
    { id: "moss",        parent: "bryophyta",        age_mya: 0, isLeaf: true, tier: 1,
      commonName: "Common moss",          sci: "Physcomitrella patens",
      funFact: "Among the first plants to colonize land; has no roots, veins, or seeds.",
      image: "common-moss", emoji: "🌱" },
    { id: "yew",         parent: "gymnospermae",     age_mya: 0, isLeaf: true, tier: 2,
      commonName: "Yew tree",             sci: "Taxus baccata",
      funFact: "One of Europe's oldest trees — some are over 4,000 years old. Its bark yielded the cancer drug Taxol.",
      image: "yew", emoji: "🌲" },
    { id: "ginkgo",      parent: "gymnospermae",     age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Ginkgo",               sci: "Ginkgo biloba",
      funFact: "A 'living fossil' unchanged for 200 million years; the sole survivor of an ancient plant lineage.",
      image: "ginkgo", emoji: "🌿" },
    { id: "water-lily",  parent: "angiosperms",      age_mya: 0, isLeaf: true, tier: 4,
      commonName: "White water lily",     sci: "Nymphaea alba",
      funFact: "Opens its flowers each morning and closes them each evening for just three days; the flowers warm themselves to attract beetles, which spend the night enclosed inside before emerging dusted with pollen.",
      image: "water-lily", emoji: "🌸" },
    { id: "rice",        parent: "monocots",         age_mya: 0, isLeaf: true, tier: 1,
      commonName: "Rice",                 sci: "Oryza sativa",
      funFact: "Feeds more than half of humanity; its genome was the first crop genome fully sequenced.",
      image: "rice", emoji: "🌾" },
    { id: "oak",         parent: "eudicots",         age_mya: 0, isLeaf: true, tier: 2,
      commonName: "English oak",          sci: "Quercus robur",
      funFact: "A single mature oak can support over 500 species of insects, birds, and mammals.",
      image: "oak", emoji: "🌳" },
    { id: "sunflower",   parent: "eudicots",         age_mya: 0, isLeaf: true, tier: 1,
      commonName: "Sunflower",            sci: "Helianthus annuus",
      funFact: "Each sunflower 'head' is actually a composite of up to 2,000 tiny individual flowers.",
      image: "sunflower", emoji: "🌻" },

    // Invertebrate animals
    { id: "sponge",      parent: "porifera",         age_mya: 0, isLeaf: true, tier: 1,
      commonName: "Sea sponge",           sci: "Spongilla lacustris",
      funFact: "Has no neurons, muscles, or organs — yet can sneeze to clear its pores, taking about 30 minutes.",
      image: "sponge", emoji: "🧽" },
    { id: "jellyfish",   parent: "cnidaria",         age_mya: 0, isLeaf: true, tier: 1,
      commonName: "Moon jellyfish",       sci: "Aurelia aurita",
      funFact: "Has no brain, heart, or blood, yet coordinates complex swimming with a diffuse nerve net.",
      image: "moon-jellyfish", emoji: "🪼" },
    { id: "earthworm",   parent: "annelida",         age_mya: 0, isLeaf: true, tier: 2,
      commonName: "Earthworm",            sci: "Lumbricus terrestris",
      funFact: "Darwin spent 40 years studying earthworms; a single acre of soil can hold over a million of them.",
      image: "earthworm", emoji: "🪱" },
    { id: "octopus",     parent: "mollusca",         age_mya: 0, isLeaf: true, tier: 5,
      commonName: "Common octopus",       sci: "Octopus vulgaris",
      funFact: "Has three hearts, blue blood, and distributed intelligence — two-thirds of its neurons are in its arms.",
      image: "common-octopus", emoji: "🐙" },
    { id: "velvet-worm", parent: "ecdysozoa",        age_mya: 0, isLeaf: true, tier: 7,
      commonName: "Velvet worm",          sci: "Peripatus juliformis",
      funFact: "A 'living fossil' nearly unchanged for 500 million years; hunts by spraying a sticky slime net from a distance.",
      image: "velvet-worm", emoji: "🐛" },
    { id: "starfish",    parent: "echinodermata",    age_mya: 0, isLeaf: true, tier: 3,
      commonName: "Common starfish",      sci: "Asterias rubens",
      funFact: "Has no brain — just a ring of nerves — yet can regenerate an entire limb from a single severed arm.",
      image: "starfish", emoji: "⭐" },
    { id: "barnacle",    parent: "crustacea",        age_mya: 0, isLeaf: true, tier: 7,
      commonName: "Acorn barnacle",       sci: "Semibalanus balanoides",
      funFact: "Darwin spent eight years studying barnacles; these sessile crustaceans cement themselves headfirst to rocks and kick food into their mouths with feathery legs.",
      image: "acorn-barnacle", emoji: "🐚" },
    { id: "sea-squirt",  parent: "tunicata",         age_mya: 0, isLeaf: true, tier: 6,
      commonName: "Sea squirt",           sci: "Ciona intestinalis",
      funFact: "Starts life as a free-swimming tadpole-like larva with a notochord, then metamorphoses into a sessile filter feeder.",
      image: "sea-squirt", emoji: "🌊" },
    { id: "spider",      parent: "arachnida",        age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Garden spider",        sci: "Araneus diadematus",
      funFact: "Silk is stronger than steel by weight; some spiders recycle it by eating their webs each morning.",
      image: "garden-spider", emoji: "🕷️" },
    { id: "horseshoecrab", parent: "chelicerata",    age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Horseshoe crab",       sci: "Limulus polyphemus",
      funFact: "Has survived largely unchanged for over 300 million years; its blue blood, which clots instantly around bacterial contamination, is used to safety-test every injectable medication.",
      image: "horseshoe-crab", emoji: "🦀" },
    { id: "fruitfly",    parent: "holometabola",     age_mya: 0, isLeaf: true, tier: 1,
      commonName: "Fruit fly",            sci: "Drosophila melanogaster",
      funFact: "The workhorse of genetics for over a century — it shares about 60% of its genes with humans.",
      image: "fruit-fly", emoji: "🪰" },
    { id: "honeybee",    parent: "holometabola",     age_mya: 0, isLeaf: true, tier: 1,
      commonName: "Honeybee",             sci: "Apis mellifera",
      funFact: "Communicates the precise direction and distance of flowers with a 'waggle dance'.",
      image: "honeybee", emoji: "🐝" },

    // Fish
    { id: "shark",       parent: "chondrichthyes",   age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Great white shark",    sci: "Carcharodon carcharias",
      funFact: "Sharks first appeared over 450 million years ago — more than 200 million years before the first dinosaurs — making them one of the oldest surviving vertebrate lineages on Earth.",
      image: "great-white-shark", emoji: "🦈" },
    { id: "zebrafish",   parent: "actinopterygii",   age_mya: 0, isLeaf: true, tier: 5,
      commonName: "Zebrafish",            sci: "Danio rerio",
      funFact: "Can fully regenerate a damaged heart — a property scientists are trying to replicate in humans.",
      image: "zebrafish", emoji: "🐟" },
    { id: "lungfish",    parent: "rhipidistia",      age_mya: 0, isLeaf: true, tier: 5,
      commonName: "African lungfish",     sci: "Protopterus annectens",
      funFact: "Breathes air with lungs and can survive droughts for up to four years encased in a dried mucus cocoon underground, its metabolism slowing to near zero.",
      image: "lungfish", emoji: "🐟" },
    { id: "coelacanth",  parent: "sarcopterygii",    age_mya: 0, isLeaf: true, tier: 8,
      commonName: "Coelacanth",           sci: "Latimeria chalumnae",
      funFact: "Thought extinct for 65 million years until a live specimen was caught in 1938; gives birth to live young.",
      image: "coelacanth", emoji: "🐠" },

    // Amphibians
    { id: "frog",        parent: "amphibia_clade",   age_mya: 0, isLeaf: true, tier: 5,
      commonName: "African clawed frog",  sci: "Xenopus laevis",
      funFact: "Was used as a live pregnancy test in the 1940s–60s: pregnant women's urine induced egg-laying.",
      image: "African-clawed-frog", emoji: "🐸" },
    { id: "axolotl",     parent: "amphibia_clade",   age_mya: 0, isLeaf: true, tier: 6,
      commonName: "Axolotl",              sci: "Ambystoma mexicanum",
      funFact: "Retains its larval features for life (neoteny) and can regenerate entire limbs, heart tissue, and parts of its brain.",
      image: "axolotl", emoji: "🦎" },

    // Reptiles
    { id: "komodo",      parent: "lepidosauria",     age_mya: 0, isLeaf: true, tier: 6,
      commonName: "Komodo dragon",        sci: "Varanus komodoensis",
      funFact: "The world's largest lizard; females can reproduce without males in a process called parthenogenesis.",
      image: "komodo-dragon", emoji: "🦎" },
    { id: "tuatara",     parent: "lepidosauria",     age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Tuatara",              sci: "Sphenodon punctatus",
      funFact: "Has a light-sensing 'third eye' on top of its skull and remains active at temperatures as low as 7 °C — colder than any other reptile; individuals have been known to live past 100 years.",
      image: "tuatara", emoji: "🦎" },
    { id: "turtle",      parent: "archelosauria",    age_mya: 0, isLeaf: true, tier: 1,
      commonName: "Green sea turtle",     sci: "Chelonia mydas",
      funFact: "Navigates thousands of kilometres using Earth's magnetic field to return to the exact beach where it hatched, decades later.",
      image: "green-sea-turtle", emoji: "🐢" },
    { id: "crocodile",   parent: "crocodilia",       age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Nile crocodile",       sci: "Crocodylus niloticus",
      funFact: "Africa's largest freshwater predator; it can bite with enough force to crush bone, yet its jaw-opening muscles are so weak its mouth can be held shut by hand.",
      image: "Nile-crocodile", emoji: "🐊" },

    // Extinct dinosaurs & pterosaurs
    { id: "triceratops", parent: "dinosauria",       age_mya: 0, isLeaf: true, tier: 7,
      commonName: "Triceratops",          sci: "Triceratops horridus",
      funFact: "Its skull — up to 2.5 m long — is one of the largest of any land animal ever, yet it was a plant-eater.",
      image: "triceratops", emoji: "🦕" },
    { id: "tyrannosaur", parent: "saurischia",       age_mya: 0, isLeaf: true, tier: 8,
      commonName: "Tyrannosaurus rex",    sci: "Tyrannosaurus rex",
      funFact: "Had the strongest bite force of any known land animal (~3,600 kg) and binocular vision as wide as a modern hawk's — more consistent with an active predator than a scavenger.",
      image: "tyrannosaur", emoji: "🦖" },
    { id: "pterosaur",   parent: "ornithodira",      age_mya: 0, isLeaf: true, tier: 8,
      commonName: "Pteranodon",           sci: "Pteranodon longiceps",
      funFact: "The first vertebrates to evolve powered flight, roughly 80 million years before birds; Pteranodon's wingspan reached up to 6 metres, yet its hollow bones kept it light enough to soar for days.",
      image: "pterosaur", emoji: "🦅" },

    // Birds
    { id: "pigeon",      parent: "inopinaves",       age_mya: 0, isLeaf: true, tier: 2,
      commonName: "Rock pigeon",          sci: "Columba livia",
      funFact: "The ancestor of all domestic pigeons; can navigate home from hundreds of kilometres away using magnetic fields and smell.",
      image: "pigeon", emoji: "🐦" },
    { id: "eagle",       parent: "inopinaves",       age_mya: 0, isLeaf: true, tier: 3,
      commonName: "Bald eagle",           sci: "Haliaeetus leucocephalus",
      funFact: "Can spot a rabbit from 3 km away; its nest can weigh over a ton after years of additions.",
      image: "bald-eagle", emoji: "🦅" },
    { id: "falcon",      parent: "australaves",      age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Peregrine falcon",     sci: "Falco peregrinus",
      funFact: "The fastest animal on Earth, reaching over 380 km/h in a dive; once nearly extinct from DDT-induced eggshell thinning, it is now one of conservation's greatest comeback stories.",
      image: "peregrine-falcon", emoji: "🦅" },
    { id: "parakeet",    parent: "australaves",      age_mya: 0, isLeaf: true, tier: 2,
      commonName: "Common parakeet",      sci: "Melopsittacus undulatus",
      funFact: "Also called the budgerigar; a budgerigar named Puck holds the Guinness record for bird vocabulary, with 1,728 words.",
      image: "parakeet", emoji: "🦜" },

    // Mammals
    { id: "platypus",    parent: "monotremata",      age_mya: 0, isLeaf: true, tier: 6,
      commonName: "Platypus",             sci: "Ornithorhynchus anatinus",
      funFact: "One of the only egg-laying mammals; males have venomous spurs on their hind legs and can sense electric fields with their bill.",
      image: "platypus", emoji: "🦆" },
    { id: "kangaroo",    parent: "marsupialia",      age_mya: 0, isLeaf: true, tier: 5,
      commonName: "Red kangaroo",         sci: "Macropus rufus",
      funFact: "Australia's largest native land animal; a joey is the size of a jellybean at birth and continues developing in the pouch.",
      image: "red-kangaroo", emoji: "🦘" },
    { id: "opossum",     parent: "marsupialia",      age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Virginia opossum",     sci: "Didelphis virginiana",
      funFact: "North America's only marsupial; 'playing possum' is an involuntary catatonic response to threat, not a conscious act.",
      image: "virginia-opossum", emoji: "🐀" },
    { id: "whale",       parent: "cetacea",          age_mya: 0, isLeaf: true, tier: 3,
      commonName: "Blue whale",           sci: "Balaenoptera musculus",
      funFact: "The largest animal ever known to exist; its heart is the size of a small car.",
      image: "blue-whale", emoji: "🐋" },
    { id: "hippo",       parent: "whippomorpha",     age_mya: 0, isLeaf: true, tier: 3,
      commonName: "Hippopotamus",         sci: "Hippopotamus amphibius",
      funFact: "Secretes a red-orange fluid from its skin that acts as a natural sunscreen and antibiotic — long mistaken by observers for sweating blood.",
      image: "hippo", emoji: "🦛" },
    { id: "giraffe",     parent: "ruminantia",       age_mya: 0, isLeaf: true, tier: 1,
      commonName: "Giraffe",              sci: "Giraffa camelopardalis",
      funFact: "Has the same number of neck vertebrae as a human (7); its heart must pump blood 2 metres up to reach its brain.",
      image: "giraffe", emoji: "🦒" },
    { id: "pronghorn",   parent: "ruminantia",       age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Pronghorn",            sci: "Antilocapra americana",
      funFact: "The fastest land animal in the Western Hemisphere, capable of sustaining 90 km/h — likely evolved to outrun extinct American cheetahs.",
      image: "pronghorn", emoji: "🦌" },
    { id: "pangolin",    parent: "ferae",            age_mya: 0, isLeaf: true, tier: 6,
      commonName: "Pangolin",             sci: "Manis temminckii",
      funFact: "The world's most trafficked mammal; its scales are made of keratin — the same material as human fingernails.",
      image: "pangolin", emoji: "🐾" },
    { id: "cat",         parent: "feliformia",       age_mya: 0, isLeaf: true, tier: 1,
      commonName: "Domestic cat",         sci: "Felis catus",
      funFact: "Technically still an apex predator — domestic cats kill an estimated 1–4 billion birds per year in the US alone.",
      image: "cat", emoji: "🐱" },
    { id: "spottedhyena", parent: "hyaenidae",       age_mya: 0, isLeaf: true, tier: 5,
      commonName: "Spotted hyena",        sci: "Crocuta crocuta",
      funFact: "Known for a complex matriarchal social structure and a vocalization that sounds like human laughter.",
      image: "spotted-hyena", emoji: "🐆" },
    { id: "aardwolf",    parent: "hyaenidae",        age_mya: 0, isLeaf: true, tier: 7,
      commonName: "Aardwolf",             sci: "Proteles cristata",
      funFact: "A specialized insectivore that can consume up to 300,000 termites in a single night using its long, sticky tongue.",
      image: "aardwolf", emoji: "🐺" },
    { id: "dog",         parent: "canidae",          age_mya: 0, isLeaf: true, tier: 1,
      commonName: "Domestic dog",         sci: "Canis lupus familiaris",
      funFact: "Domesticated from wolves at least 15,000 years ago — the first species humans ever domesticated.",
      image: "dog", emoji: "🐶" },
    { id: "red-fox",     parent: "canidae",          age_mya: 0, isLeaf: true, tier: 3,
      commonName: "Red fox",              sci: "Vulpes vulpes",
      funFact: "The most widely distributed wild carnivore on Earth, found from Arctic tundra to city suburbs across Europe, Asia, North America, and — through introduction — Australia.",
      image: "red-fox", emoji: "🦊" },
    { id: "panda",       parent: "arctoidea",        age_mya: 0, isLeaf: true, tier: 3,
      commonName: "Giant panda",          sci: "Ailuropoda melanoleuca",
      funFact: "Eats almost exclusively bamboo, yet is biologically classified as a carnivore; its apparent 'thumb' is an enlarged wrist bone, not a true digit.",
      image: "giant-panda", emoji: "🐼" },
    { id: "seal",        parent: "arctoidea",        age_mya: 0, isLeaf: true, tier: 6,
      commonName: "Harbor seal",         sci: "Phoca vitulina",
      funFact: "Can slow its heartbeat to just 4 beats per minute while diving and stay underwater for over 30 minutes.",
      image: "harbor-seal", emoji: "🦭" },
    { id: "giant-anteater", parent: "xenarthra",     age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Giant anteater",       sci: "Myrmecophaga tridactyla",
      funFact: "Has no teeth at all; its tongue flicks in and out 150 times per minute to lap up 35,000 ants and termites per day.",
      image: "giant-anteater", emoji: "🐜" },
    { id: "elephant",    parent: "proboscidea",      age_mya: 0, isLeaf: true, tier: 1,
      commonName: "African bush elephant", sci: "Loxodonta africana",
      funFact: "The largest land animal alive; uses infrasound calls below human hearing to communicate over kilometres.",
      image: "African-elephant", emoji: "🐘" },
    { id: "elephant-shrew", parent: "afrotheria",    age_mya: 0, isLeaf: true, tier: 6,
      commonName: "Elephant shrew",       sci: "Elephantulus sp.", wiki: "Elephant shrew",
      funFact: "Despite weighing as little as 50 g, can sprint at nearly 30 km/h; it maintains a network of private escape trails through leaf litter, which it patrols and sweeps clear of debris each day.",
      image: "elephant-shrew", emoji: "🐭" },
    { id: "human",       parent: "hominidae",        age_mya: 0, isLeaf: true, tier: 3,
      commonName: "Human",                sci: "Homo sapiens",
      funFact: "The only species known to cook food, which may have driven the dramatic expansion of the brain.",
      image: "human", emoji: "🧑" },
    { id: "chimp",       parent: "hominidae",        age_mya: 0, isLeaf: true, tier: 1,
      commonName: "Chimpanzee",           sci: "Pan troglodytes",
      funFact: "Shares ~98.7% of DNA with humans; makes and uses tools, and has been observed in warfare between groups.",
      image: "chimp", emoji: "🐒" },
    { id: "mouse",       parent: "muridae",          age_mya: 0, isLeaf: true, tier: 1,
      commonName: "House mouse",          sci: "Mus musculus",
      funFact: "Shares ~85% of protein-coding genes with humans, making it an indispensable model for medicine.",
      image: "mouse", emoji: "🐭" },
    { id: "rat",         parent: "muridae",          age_mya: 0, isLeaf: true, tier: 2,
      commonName: "Brown rat",            sci: "Rattus norvegicus",
      funFact: "Laughs at ultrasonic frequencies when tickled, and can be trained to sniff out tuberculosis and landmines.",
      image: "rat", emoji: "🐀" },
    { id: "hamster",     parent: "rodentia",         age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Syrian hamster",       sci: "Mesocricetus auratus",
      funFact: "Can store food in cheek pouches that stretch back to their hips; wild hamsters run up to 9 km a night.",
      image: "Syrian-hamster", emoji: "🐹" },
    { id: "rabbit",      parent: "glires",           age_mya: 0, isLeaf: true, tier: 2,
      commonName: "Domesticated rabbit",  sci: "Oryctolagus cuniculus",
      funFact: "Rabbits eat their own droppings once to extract extra nutrients — a process called cecotrophy.",
      image: "rabbit", emoji: "🐰" },
  ]
};

// Allow loading in Node.js (for checks/ and tests/)
if (typeof module !== 'undefined') module.exports = phylogeny;
