const phylogeny = {
  nodes: [

    // ── Domains ───────────────────────────────────────────────────────────────
    { id: "root",             parent: null,               age_mya: 3800,
      label: "life",                     sci: "LUCA",  wiki: "Last_universal_common_ancestor",
      trait: "the common ancestor of all known life on Earth" },
    { id: "bacteria",         parent: "root",             age_mya: 3500,
      label: "bacteria",                 sci: "Bacteria",
      trait: "single-celled organisms lacking a nucleus, typically with rigid peptidoglycan cell walls" },
    // Under the two-domain model, eukaryotes evolved from within Archaea (the Asgard lineage),
    // so "Archaea" is a grade (paraphyletic).  The monophyletic Archaea clade includes eukaryotes.
    { id: "archaea",          parent: "root",             age_mya: 3500,
      label: "archaea",                  sci: "Archaea",
      trait: "single-celled organisms resembling bacteria in size but with fundamentally distinct membrane chemistry and molecular machinery" },
    // Euryarchaeota: deep-branching archaeal lineage (methanogen's phylum); most distantly related to eukaryotes
    { id: "euryarchaeota",    parent: "archaea",          age_mya: 3400,
      label: "euryarchaeotes",           sci: "Euryarchaeota",
      trait: "diverse archaea including methane producers, extreme halophiles, and high-temperature thermophiles" },
    // Asgard archaea + eukaryotes: the clade within which eukaryotes are nested
    { id: "asgard_eukarya",   parent: "archaea",          age_mya: 2600,
      label: "Asgard archaea and eukaryotes", sci: "Asgardarchaeota + Eukaryota", wiki: "Asgard_archaea",
      trait: "the clade demonstrating that eukaryotes evolved from within archaea rather than alongside them" },
    { id: "eukarya",          parent: "asgard_eukarya",   age_mya: 2100,
      label: "eukaryotes",               sci: "Eukaryota",
      trait: "organisms whose cells contain DNA enclosed in a membrane-bound nucleus" },

    // ── Major eukaryote lineages ───────────────────────────────────────────────
    // Amorphea (= Unikonta): opisthokonts + amoebozoans — sister to Diaphoretickes
    { id: "amorphea",         parent: "eukarya",          age_mya: 1800,
      label: "amorpheans",               sci: "Amorphea",
      trait: "the eukaryote supergroup that gave rise to animals, fungi, and amoebae" },
    // Diaphoretickes (= Bikonta): SAR + Archaeplastida
    { id: "diaphoretickes",   parent: "eukarya",          age_mya: 1500,
      label: "diaphoretickes",           sci: "Diaphoretickes",
      trait: "a major eukaryote supergroup including algae, plants, and diverse protists" },
    // SAR supergroup: Stramenopiles + Alveolates + Rhizaria
    { id: "sar",              parent: "diaphoretickes",   age_mya: 1100,
      label: "SAR supergroup",           sci: "SAR",   wiki: "SAR_supergroup",
      trait: "a vast assemblage of mostly microscopic eukaryotes united by molecular evidence, including diatoms, dinoflagellates, and water moulds" },
    { id: "stramenopila",     parent: "sar",              age_mya: 1000,
      label: "stramenopiles",            sci: "Stramenopila",
      trait: "eukaryotes with distinctive bristle-tipped flagella, including diatoms, kelp, and water moulds" },
    { id: "alveolata",        parent: "sar",              age_mya: 1000,
      label: "alveolates",               sci: "Alveolata",
      trait: "eukaryotes with a layer of flattened membrane sacs (alveoli) just beneath the cell surface" },
    // Archaeplastida: red algae + green algae + land plants
    { id: "archaeplastida",   parent: "diaphoretickes",   age_mya: 1200,
      label: "archaeplastids",           sci: "Archaeplastida",
      trait: "eukaryotes that gained photosynthesis by permanently engulfing a cyanobacterium roughly 1.5 billion years ago" },
    { id: "opisthokonta",     parent: "amorphea",         age_mya: 1525,
      label: "opisthokonts",             sci: "Opisthokonta",
      trait: "eukaryotes whose motile cells swim with a single posterior flagellum — the supergroup containing both animals and fungi" },
    { id: "plants_clade",     parent: "archaeplastida",   age_mya: 475,
      label: "land plants",              sci: "Embryophyta",
      trait: "photosynthetic organisms adapted to terrestrial life, with a waxy cuticle and embryos retained within the parent plant" },

    // ── Fungi ─────────────────────────────────────────────────────────────────
    { id: "fungi",            parent: "opisthokonta",     age_mya: 1000,
      label: "fungi",                    sci: "Fungi",
      trait: "heterotrophs that digest food outside their bodies by secreting enzymes, then absorb the dissolved nutrients" },
    { id: "ascomycota",       parent: "fungi",            age_mya: 600,
      label: "sac fungi",                sci: "Ascomycota",
      trait: "fungi that produce spores inside microscopic sac-like cells called asci" },
    { id: "basidiomycota",    parent: "fungi",            age_mya: 600,
      label: "club fungi",               sci: "Basidiomycota",
      trait: "fungi that bear spores on club-shaped cells (basidia), including most familiar mushrooms and toadstools" },

    // ── Animals: basal ────────────────────────────────────────────────────────
    { id: "animalia",         parent: "opisthokonta",     age_mya: 800,
      label: "animals",                  sci: "Animalia",
      trait: "multicellular organisms that obtain energy by ingesting other organisms" },
    { id: "porifera",         parent: "animalia",         age_mya: 700,
      label: "sponges",                  sci: "Porifera",
      trait: "sessile animals that lack true tissues and feed by pumping water through pores in their body" },
    { id: "eumetazoa",        parent: "animalia",         age_mya: 650,
      label: "eumetazoans",              sci: "Eumetazoa",
      trait: "animals with true tissues, a nervous system, and specialised cell types" },
    { id: "cnidaria",         parent: "eumetazoa",        age_mya: 600,
      label: "cnidarians",               sci: "Cnidaria",
      trait: "radially symmetrical animals armed with stinging cells (nematocysts)" },
    { id: "bilateria",        parent: "eumetazoa",        age_mya: 555,
      label: "bilaterians",              sci: "Bilateria",
      trait: "animals with bilateral body symmetry, three embryonic tissue layers, and a through-gut" },

    // ── Protostomes ───────────────────────────────────────────────────────────
    { id: "protostomia",      parent: "bilateria",        age_mya: 550,
      label: "protostomes",              sci: "Protostomia",
      trait: "bilaterians in which the embryonic mouth opening becomes the adult mouth" },
    { id: "ecdysozoa",        parent: "protostomia",      age_mya: 540,
      label: "ecdysozoans",              sci: "Ecdysozoa",
      trait: "animals that grow by periodically shedding (moulting) their outer cuticle or exoskeleton" },
    { id: "lophotrochozoa",   parent: "protostomia",      age_mya: 530,
      label: "lophotrochozoans",         sci: "Lophotrochozoa",
      trait: "protostomes that grow continuously rather than by moulting, including molluscs, annelids, and flatworms" },
    { id: "arthropoda",       parent: "ecdysozoa",        age_mya: 520,
      label: "arthropods",               sci: "Arthropoda",
      trait: "animals with a hard exoskeleton, segmented body, and jointed appendages" },
    { id: "chelicerata",      parent: "arthropoda",       age_mya: 480,
      label: "chelicerates",             sci: "Chelicerata",
      trait: "arthropods with pincer-like or fang-like first appendages (chelicerae) rather than antennae or jaws" },
    { id: "arachnida",        parent: "chelicerata",      age_mya: 430,
      label: "arachnids",                sci: "Arachnida",
      trait: "eight-legged chelicerates with a body divided into two main segments" },
    { id: "mandibulata",      parent: "arthropoda",       age_mya: 480,
      label: "mandibulates",             sci: "Mandibulata",
      trait: "arthropods with jaw-like mandibles as their primary biting and chewing mouthparts" },
    { id: "crustacea",        parent: "mandibulata",      age_mya: 450,
      label: "crustaceans",              sci: "Crustacea",
      trait: "mandibulate arthropods with two pairs of antennae and gills" },
    { id: "insecta",          parent: "mandibulata",      age_mya: 400,
      label: "insects",                  sci: "Insecta",
      trait: "arthropods with six legs, three body segments (head, thorax, abdomen), and usually one or two pairs of wings" },
    { id: "paraneoptera",     parent: "insecta",          age_mya: 380,
      label: "true bugs and allies",     sci: "Paraneoptera",
      trait: "insects with piercing–sucking mouthparts and incomplete metamorphosis, including true bugs, thrips, and lice" },
    { id: "holometabola",     parent: "insecta",          age_mya: 300,
      label: "holometabolans",           sci: "Holometabola",
      trait: "insects that develop through four completely distinct life stages: egg, larva, pupa, and adult" },
    { id: "panorpida",        parent: "holometabola",     age_mya: 270,
      label: "flies, moths, and butterflies", sci: "Panorpida",
      trait: "holometabolans united by molecular evidence, including all flies, moths, butterflies, and fleas" },
    { id: "mollusca",         parent: "lophotrochozoa",   age_mya: 530,
      label: "molluscs",                 sci: "Mollusca",
      trait: "soft-bodied animals, usually with a calcium carbonate shell and a rasping ribbon-like tongue (radula)" },
    { id: "annelida",         parent: "lophotrochozoa",   age_mya: 530,
      label: "annelids",                 sci: "Annelida",
      trait: "worm-like animals whose bodies are divided into a series of repeating ring-like segments" },

    // ── Deuterostomes ─────────────────────────────────────────────────────────
    { id: "deuterostomia",    parent: "bilateria",        age_mya: 550,
      label: "deuterostomes",            sci: "Deuterostomia",
      trait: "bilaterians in which the embryonic blastopore becomes the anus, not the mouth" },
    { id: "echinodermata",    parent: "deuterostomia",    age_mya: 520,
      label: "echinoderms",              sci: "Echinodermata",
      trait: "marine animals with five-fold radial symmetry and a hydraulic tube-foot system" },
    { id: "chordata",         parent: "deuterostomia",    age_mya: 520,
      label: "chordates",                sci: "Chordata",
      trait: "animals that have, at some point in development, a notochord, a dorsal hollow nerve cord, and pharyngeal slits" },
    { id: "tunicata",         parent: "chordata",         age_mya: 520,
      label: "tunicates",                sci: "Tunicata",
      trait: "filter-feeding chordates that are free-swimming as larvae but typically sessile as adults" },
    { id: "vertebrata",       parent: "chordata",         age_mya: 480,
      label: "vertebrates",              sci: "Vertebrata",
      trait: "chordates with a segmented backbone protecting the spinal cord" },
    { id: "chondrichthyes",   parent: "vertebrata",       age_mya: 450,
      label: "cartilaginous fishes",     sci: "Chondrichthyes",
      trait: "vertebrates with a skeleton made entirely of cartilage — sharks, rays, and chimaeras" },
    { id: "osteichthyes",     parent: "vertebrata",       age_mya: 450,
      label: "bony vertebrates",         sci: "Osteichthyes",
      trait: "vertebrates with an internal skeleton primarily of bone" },
    { id: "actinopterygii",   parent: "osteichthyes",     age_mya: 430,
      label: "ray-finned fishes",        sci: "Actinopterygii",
      trait: "bony vertebrates whose fins are supported by thin, rigid bony spines called fin rays" },
    { id: "sarcopterygii",    parent: "osteichthyes",     age_mya: 430,
      label: "lobe-finned fishes",       sci: "Sarcopterygii",
      trait: "bony vertebrates with fleshy lobed fins or limbs, each supported by a single proximal bone" },
    // Rhipidistia: lungfishes + tetrapods (sister to coelacanths within Sarcopterygii)
    { id: "rhipidistia",      parent: "sarcopterygii",    age_mya: 415,
      label: "rhipidistians",            sci: "Rhipidistia",
      trait: "lobe-finned vertebrates ancestral to all four-limbed animals, including lungfishes and tetrapods" },
    { id: "tetrapoda",        parent: "rhipidistia",      age_mya: 375,
      label: "tetrapods",                sci: "Tetrapoda",
      trait: "vertebrates with four limbs, or descended from four-limbed ancestors" },
    { id: "amphibia_clade",   parent: "tetrapoda",        age_mya: 360,
      label: "amphibians",               sci: "Amphibia",
      trait: "tetrapods that typically hatch as aquatic, gill-breathing larvae before metamorphosing into semi-terrestrial adults" },
    { id: "amniota",          parent: "tetrapoda",        age_mya: 320,
      label: "amniotes",                 sci: "Amniota",
      hint: "basically mammals and reptiles",
      trait: "tetrapods whose embryos develop inside a fluid-filled amnion, freeing reproduction from standing water" },

    // ── Reptiles, birds & dinosaurs ───────────────────────────────────────────
    { id: "sauropsida",       parent: "amniota",          age_mya: 310,
      label: "reptiles and birds",       sci: "Sauropsida",
      trait: "amniotes with temporal openings in the skull that accommodate large jaw muscles — the lineage of all living reptiles and birds" },
    { id: "lepidosauria",     parent: "sauropsida",       age_mya: 280,
      label: "lepidosaurs",              sci: "Lepidosauria",
      trait: "reptiles with overlapping scales and a transverse cloacal opening, including lizards, snakes, and tuatara" },
    // Squamata: lizards + snakes (tuatara is Rhynchocephalia, the lepidosaur outgroup)
    { id: "squamata",         parent: "lepidosauria",     age_mya: 240,
      label: "scaled reptiles",              sci: "Squamata",
      trait: "the most species-rich reptile order, with over 10,000 species of lizards and snakes united by a kinetic skull that allows a wide gape" },
    { id: "gekkota",          parent: "squamata",         age_mya: 200,
      label: "geckos",                       sci: "Gekkota",
      trait: "lizards whose toes bear microscopic hair-like setae that adhere to smooth surfaces via van der Waals forces — allowing many species to climb glass or walk on ceilings" },
    { id: "toxicofera",       parent: "squamata",         age_mya: 170,
      label: "toxicoferans",                 sci: "Toxicofera",
      trait: "the largest squamate clade, comprising all snakes and most lizards — united by molecular evidence of an ancient shared venomous ancestry" },
    { id: "serpentes",        parent: "toxicofera",       age_mya: 150,
      label: "snakes",                       sci: "Serpentes",
      trait: "elongated, limbless toxicoferans that evolved from burrowing lizard ancestors, with fused eyelids and a highly kinetic skull for swallowing prey whole" },
    // Archelosauria: turtles + archosaurs (molecular consensus; turtles nest within diapsids)
    { id: "archelosauria",    parent: "sauropsida",       age_mya: 255,
      label: "archelosaurs",             sci: "Archelosauria",
      trait: "the reptile group more closely related to birds than to lizards, including turtles, crocodilians, and birds" },
    { id: "archosauria",      parent: "archelosauria",    age_mya: 245,
      label: "archosaurs",               sci: "Archosauria",
      trait: "reptiles with distinctive skull openings in front of the eye socket and in the ankle region" },
    { id: "crocodilia",       parent: "archosauria",      age_mya: 95,
      label: "crocodilians",             sci: "Crocodilia",
      trait: "the only living non-avian archosaurs, with an armoured back, socketed teeth, and a four-chambered heart" },
    // Ornithodira: pterosaurs + dinosaurs (including all modern birds)
    { id: "ornithodira",      parent: "archosauria",      age_mya: 240,
      label: "ornithodirans",            sci: "Ornithodira",
      trait: "archosaurs with an upright gait and hind limbs positioned directly beneath the body" },
    // Dinosauria includes birds; Saurischia (theropods) contains T. rex and Aves as sister groups
    { id: "dinosauria",       parent: "ornithodira",      age_mya: 235,
      label: "dinosaurs",                sci: "Dinosauria",
      trait: "ornithodirans characterised by an open hip socket that allows a fully upright posture" },
    { id: "saurischia",       parent: "dinosauria",       age_mya: 230,
      label: "saurischians",             sci: "Saurischia",
      trait: "dinosaurs with a lizard-like hip arrangement, including theropods (ancestors of birds) and giant sauropods" },
    { id: "aves",             parent: "saurischia",       age_mya: 95,
      label: "birds",                    sci: "Aves",
      trait: "feathered dinosaurs with a wishbone, hollow bones, and a keeled sternum" },
    // Inopinaves: pigeons + eagles + many others; Australaves: falcons + parrots
    { id: "inopinaves",       parent: "aves",             age_mya: 70,
      label: "inopinaves",               sci: "Inopinaves",
      trait: "a large bird clade including doves, flamingos, wading birds, and most raptors" },
    { id: "australaves",      parent: "aves",             age_mya: 70,
      label: "australaves",              sci: "Australaves",
      trait: "the bird clade uniting falcons, parrots, and all songbirds" },

    // ── Mammals ───────────────────────────────────────────────────────────────
    { id: "mammalia",         parent: "amniota",          age_mya: 310,
      label: "mammals",                  sci: "Mammalia",
      trait: "warm-blooded vertebrates with hair that nurse their young on milk" },
    { id: "monotremata",      parent: "mammalia",         age_mya: 180,
      label: "monotremes",               sci: "Monotremata",
      trait: "egg-laying mammals that still nurse their young on milk secreted through the skin" },
    { id: "theria",           parent: "mammalia",         age_mya: 180,
      label: "therians",                 sci: "Theria",
      trait: "mammals that give birth to live young rather than laying eggs" },
    { id: "marsupialia",      parent: "theria",           age_mya: 80,
      label: "marsupials",               sci: "Marsupialia",
      trait: "therians whose young are born at a very early stage and complete development in a pouch" },
    { id: "placentalia",      parent: "theria",           age_mya: 105,
      label: "placental mammals",        sci: "Placentalia",
      trait: "therians that nourish their young in the womb through a placenta before birth" },
    // Atlantogenata: Xenarthra + Afrotheria; Boreoeutheria: Laurasiatheria + Euarchontoglires
    { id: "atlantogenata",    parent: "placentalia",      age_mya: 90,
      label: "atlantogenatans",          sci: "Atlantogenata",
      trait: "the placental superorder comprising xenarthrans and afrotherians — two groups that separated early in the southern continents" },
    { id: "boreoeutheria",    parent: "placentalia",      age_mya: 90,
      label: "boreoutherians",           sci: "Boreoeutheria",
      trait: "placental mammals that diversified primarily in the Northern Hemisphere, including carnivorans, rodents, and primates" },
    { id: "xenarthra",        parent: "atlantogenata",    age_mya: 90,
      label: "xenarthrans",              sci: "Xenarthra",
      trait: "placental mammals with extra joints in their vertebrae, including sloths, anteaters, and armadillos" },
    { id: "afrotheria",       parent: "atlantogenata",    age_mya: 90,
      label: "afrotherians",             sci: "Afrotheria",
      trait: "a diverse group of placental mammals that share a common African origin, including elephants, hyraxes, and aardvarks" },
    // Paenungulata: elephants + hyraxes + sirenians
    { id: "paenungulata",     parent: "afrotheria",       age_mya: 75,
      label: "paenungulates",                sci: "Paenungulata",
      trait: "the afrotherian clade uniting elephants, hyraxes, and sirenians — strikingly diverse in form yet sharing a recent common ancestry" },
    { id: "sirenia",          parent: "paenungulata",     age_mya: 50,
      label: "sirenians",                    sci: "Sirenia",
      trait: "fully aquatic afrotherians related to elephants, propelled by a horizontal tail fluke and subsisting entirely on aquatic vegetation" },
    { id: "proboscidea",      parent: "paenungulata",     age_mya: 65,
      label: "elephants",                sci: "Proboscidea",
      trait: "the largest living land animals, with a prehensile muscular trunk and elongated upper incisor tusks" },
    { id: "laurasiatheria",   parent: "boreoeutheria",    age_mya: 90,
      label: "laurasiatherians",         sci: "Laurasiatheria",
      trait: "placental mammals that diversified on the ancient northern landmass Laurasia, including carnivorans, bats, and hoofed mammals" },
    { id: "euarchontoglires", parent: "boreoeutheria",    age_mya: 90,
      label: "euarchontoglirans",        sci: "Euarchontoglires",
      trait: "the placental superorder uniting primates, rodents, rabbits, and their close relatives" },
    // Ferae: carnivorans + pangolins
    { id: "ferae",            parent: "laurasiatheria",   age_mya: 85,
      label: "ferae",                    sci: "Ferae",
      trait: "placental mammals united by a shared carnivorous ancestry — carnivorans and pangolins" },
    { id: "carnivora",        parent: "ferae",            age_mya: 42,
      label: "carnivorans",              sci: "Carnivora",
      trait: "placental mammals with blade-like carnassial teeth specialised for shearing flesh" },
    { id: "feliformia",       parent: "carnivora",        age_mya: 40,
      label: "cat-like carnivorans",     sci: "Feliformia",
      trait: "carnivorans with retractile or semi-retractile claws and a round pupil, including cats, hyenas, mongooses, and civets" },
    { id: "hyaenidae",        parent: "feliformia",       age_mya: 15,
      label: "hyenas and aardwolves",    sci: "Hyaenidae",
      trait: "feliform carnivorans with a sloping back, longer forelimbs than hindlimbs, and powerful jaws" },
    { id: "felidae",          parent: "feliformia",       age_mya: 25,
      label: "cats",                     sci: "Felidae",
      trait: "obligate carnivores with highly specialised shearing teeth, retractile claws, and forward-facing eyes" },
    { id: "caniformia",       parent: "carnivora",        age_mya: 40,
      label: "dog-like carnivorans",     sci: "Caniformia",
      trait: "carnivorans typically with non-retractile claws and an elongated muzzle, including dogs, bears, weasels, and seals" },
    { id: "canidae",          parent: "caniformia",       age_mya: 12,
      label: "canids",                   sci: "Canidae",
      trait: "social caniform carnivorans with long legs, bushy tails, and complex cooperative behaviours" },
    { id: "canis",            parent: "canidae",          age_mya: 1,
      label: "wolves and dogs",          sci: "Canis",
      trait: "the genus of large canids including wolves, dogs, coyotes, and jackals" },
    // Arctoidea: bears (incl. giant panda) + pinnipeds (seals etc.) within Caniformia
    { id: "arctoidea",        parent: "caniformia",       age_mya: 38,
      label: "arctoids",                 sci: "Arctoidea",
      trait: "the bear-like caniform clade, including bears, weasels, raccoons, and pinnipeds (seals and sea lions)" },
    // Euungulata: odd-toed + even-toed ungulates — sister to Ferae within Laurasiatheria
    { id: "euungulata",       parent: "laurasiatheria",   age_mya: 80,
      label: "odd- and even-toed ungulates", sci: "Euungulata",
      trait: "the laurasiatherian clade containing all hoofed mammals — rhinos and horses alongside camels, deer, and whales" },
    { id: "perissodactyla",   parent: "euungulata",       age_mya: 55,
      label: "odd-toed ungulates",           sci: "Perissodactyla",
      trait: "hoofed mammals that bear weight on an odd number of toes — horses, rhinos, and tapirs" },
    // Cetartiodactyla: even-toed ungulates + whales
    { id: "cetartiodactyla",  parent: "euungulata",       age_mya: 60,
      label: "even-toed ungulates and whales", sci: "Cetartiodactyla",
      trait: "hoofed mammals with an even number of toes — or, for whales, descended from even-toed ancestors" },
    // Cetruminantia: ruminants + whippomorphs, sister to camelids within Cetartiodactyla
    { id: "cetruminantia",    parent: "cetartiodactyla",  age_mya: 58,
      label: "ruminants and cetaceans",      sci: "Cetruminantia",
      trait: "the artiodactyl clade uniting ruminants with hippos and whales — sister to the camelids" },
    // Camelidae: Old World (Bactrian, dromedary) + New World (llama, alpaca) camelids
    { id: "camelidae",        parent: "cetartiodactyla",  age_mya: 25,
      label: "camelids",                     sci: "Camelidae",
      trait: "even-toed ungulates with an unusual three-chambered stomach, oval red blood cells resistant to dehydration, and fat stored as a hump or reserves across the back" },
    { id: "new_world_camelids", parent: "camelidae",      age_mya: 3,
      label: "New World camelids",           sci: "Lamini",
      trait: "the South American branch of the camelid family — llamas, alpacas, guanacos, and vicuñas — descended from North American ancestors that migrated south during the Great American Biotic Interchange" },
    // Whippomorpha: hippos + cetaceans (closest relatives)
    { id: "whippomorpha",     parent: "cetruminantia",    age_mya: 55,
      label: "whippomorphs",             sci: "Whippomorpha",
      trait: "the group uniting hippos and cetaceans — each other's closest living relatives" },
    { id: "cetacea",          parent: "whippomorpha",     age_mya: 50,
      label: "whales and dolphins",      sci: "Cetacea",
      trait: "fully aquatic placental mammals propelled by horizontal tail flukes, without external hind limbs" },
    { id: "mysticeti",        parent: "cetacea",          age_mya: 35,
      label: "baleen whales",                sci: "Mysticeti",
      trait: "cetaceans that replaced teeth with baleen plates — curtains of keratin bristles used to strain vast quantities of krill and small fish" },
    { id: "odontoceti",       parent: "cetacea",          age_mya: 35,
      label: "toothed whales",               sci: "Odontoceti",
      trait: "cetaceans that retained teeth and evolved sophisticated biosonar — echolocation using a fatty lens in the forehead called the melon" },
    { id: "ruminantia",       parent: "cetruminantia",    age_mya: 50,
      label: "ruminants",                sci: "Ruminantia",
      trait: "even-toed ungulates with a multi-chambered stomach for fermenting plant material and re-chewing cud" },
    { id: "primates",         parent: "euarchontoglires", age_mya: 85,
      label: "primates",                 sci: "Primates",
      trait: "mammals with grasping digits, forward-facing eyes giving stereoscopic vision, and an enlarged brain" },
    // Glires: rodents + lagomorphs
    { id: "glires",           parent: "euarchontoglires", age_mya: 80,
      label: "glires",                   sci: "Glires",
      trait: "gnawing mammals — rodents and rabbits — with ever-growing incisors and no canine teeth" },
    { id: "rodentia",         parent: "glires",           age_mya: 75,
      label: "rodents",                  sci: "Rodentia",
      trait: "the most species-rich mammal order, each with one pair of ever-growing chisel-like incisors" },
    // Muridae: Old World mice and rats (mouse + rat); sister to cricetids (hamster) within Rodentia
    { id: "muridae",          parent: "rodentia",         age_mya: 30,
      label: "Old World mice and rats",  sci: "Muridae",
      trait: "the largest family of mammals, with over 700 species of rats, mice, and their relatives" },
    { id: "hominidae",        parent: "primates",         age_mya: 15,
      label: "great apes",               sci: "Hominidae",
      trait: "the great apes: orangutans, gorillas, chimpanzees, bonobos, and humans" },

    // ── Plants ────────────────────────────────────────────────────────────────
    { id: "bryophyta",        parent: "plants_clade",     age_mya: 470,
      label: "bryophytes",               sci: "Bryophyta",
      trait: "non-vascular land plants — mosses, liverworts, and hornworts — lacking true roots and internal water-conducting tissue" },
    { id: "tracheophyta",     parent: "plants_clade",     age_mya: 430,
      label: "vascular plants",          sci: "Tracheophyta",
      trait: "plants with specialised internal plumbing (xylem and phloem) to transport water and nutrients throughout the body" },
    { id: "gymnospermae",     parent: "tracheophyta",     age_mya: 310,
      label: "gymnosperms",              sci: "Gymnospermae",
      trait: "vascular plants whose seeds are borne naked and exposed rather than enclosed in a fruit — conifers, cycads, and ginkgo" },
    { id: "angiosperms",      parent: "tracheophyta",     age_mya: 160,
      label: "flowering plants",         sci: "Angiospermae",
      trait: "vascular plants that enclose their seeds within a fruit — the dominant plant group on land today" },
    // Water lilies (Nymphaeales) are basal angiosperms, sister to core angiosperms
    { id: "core_angiosperms", parent: "angiosperms",      age_mya: 140,
      label: "core angiosperms",         sci: "Mesangiospermae",
      trait: "the major clade of flowering plants comprising almost all familiar trees, herbs, and crops" },
    { id: "monocots",         parent: "core_angiosperms", age_mya: 140,
      label: "monocots",                 sci: "Monocotyledoneae",
      trait: "flowering plants with one seed leaf, parallel-veined leaves, and flower parts in multiples of three" },
    { id: "eudicots",         parent: "core_angiosperms", age_mya: 125,
      label: "eudicots",                 sci: "Eudicotyledoneae",
      trait: "flowering plants with two seed leaves, net-veined leaves, and flower parts in fours or fives" },

    // ── Leaf organisms ────────────────────────────────────────────────────────
    // tier 1–9 unlock system (tier 1 = available from start, unlocked via XP above that)

    // Prokaryotes
    { id: "ecoli",       parent: "bacteria",         age_mya: 0, isLeaf: true, tier: 5,
      commonName: "E. coli",              sci: "Escherichia coli",
      funFact: "One of the most studied organisms on Earth, yet most strains are harmless gut residents.",
      image: "e-coli", emoji: "🦠" },
    { id: "cyanobacteria", parent: "bacteria",       age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Cyanobacteria",        sci: "Anabaena sp.", wiki: "Cyanobacteria",
      funFact: "Evolved oxygenic photosynthesis over 2.7 billion years ago, gradually saturating the atmosphere with oxygen — a transformation so radical it is called the Great Oxidation Event.",
      image: "cyanobacteria", emoji: "🌿" },
    { id: "methanogen",  parent: "euryarchaeota",    age_mya: 0, isLeaf: true, tier: 7,
      commonName: "Methanogen",           sci: "Methanocaldococcus jannaschii",
      funFact: "Produces methane as a metabolic byproduct; found in deep-sea hydrothermal vents at 85 °C.",
      image: "methanogen", emoji: "♨️" },

    // Protists
    { id: "kelp",        parent: "stramenopila",     age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Giant kelp",           sci: "Macrocystis pyrifera",
      funFact: "Grows up to 60 cm per day and forms underwater forests that shelter thousands of species.",
      image: "giant-kelp", emoji: "🌊" },
    { id: "plasmodium",  parent: "alveolata",        age_mya: 0, isLeaf: true, tier: 7,
      commonName: "Malaria parasite",     sci: "Plasmodium falciparum",
      funFact: "Responsible for the deadliest infectious disease in human history.",
      image: "malaria", emoji: "🦟" },

    // Fungi
    { id: "yeast",       parent: "ascomycota",       age_mya: 0, isLeaf: true, tier: 6,
      commonName: "Baker's yeast",        sci: "Saccharomyces cerevisiae",
      funFact: "Has been fermenting bread and beer for at least 9,000 years, yet shares ~23% of genes with humans.",
      image: "bakers-yeast", emoji: "🍞" },
    { id: "moldneurospora", parent: "ascomycota",    age_mya: 0, isLeaf: true, tier: 8,
      commonName: "Bread mold",           sci: "Neurospora crassa",
      funFact: "Showed that one gene makes one enzyme — a foundational experiment of molecular biology.",
      image: "bread-mold", emoji: "🍞" },
    { id: "mushroom",    parent: "basidiomycota",    age_mya: 0, isLeaf: true, tier: 5,
      commonName: "Button mushroom",      sci: "Agaricus bisporus",
      funFact: "White button, cremini, and portobello are all the same species: white is an albino strain, while cremini and portobello are the same brown strain at young and mature ages.",
      image: "button-mushroom", emoji: "🍄" },

    // Plants
    { id: "moss",        parent: "bryophyta",        age_mya: 0, isLeaf: true, tier: 1,
      commonName: "Common moss",          sci: "Physcomitrella patens",
      funFact: "Among the first plants to colonize land; has no roots, veins, or seeds.",
      image: "common-moss", emoji: "🌱" },
    { id: "yew",         parent: "gymnospermae",     age_mya: 0, isLeaf: true, tier: 2,
      commonName: "Yew tree",             sci: "Taxus baccata",
      funFact: "One of Europe's oldest trees — some are over 4,000 years old. Its bark yielded the cancer drug Taxol.",
      image: "yew", emoji: "🌲" },
    { id: "ginkgo",      parent: "gymnospermae",     age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Ginkgo",               sci: "Ginkgo biloba",
      funFact: "A 'living fossil' unchanged for 200 million years; the sole survivor of an ancient plant lineage.",
      image: "ginkgo", emoji: "🌿" },
    { id: "water-lily",  parent: "angiosperms",      age_mya: 0, isLeaf: true, tier: 4,
      commonName: "White water lily",     sci: "Nymphaea alba",
      funFact: "Opens its flowers each morning and closes them each evening for just three days; the flowers warm themselves to attract beetles, which spend the night enclosed inside before emerging dusted with pollen.",
      image: "water-lily", emoji: "🌸" },
    { id: "rice",        parent: "monocots",         age_mya: 0, isLeaf: true, tier: 1,
      commonName: "Rice",                 sci: "Oryza sativa",
      funFact: "Feeds more than half of humanity; its genome was the first crop genome fully sequenced.",
      image: "rice", emoji: "🌾" },
    { id: "oak",         parent: "eudicots",         age_mya: 0, isLeaf: true, tier: 2,
      commonName: "English oak",          sci: "Quercus robur",
      funFact: "A single mature oak can support over 500 species of insects, birds, and mammals.",
      image: "oak", emoji: "🌳" },
    { id: "sunflower",   parent: "eudicots",         age_mya: 0, isLeaf: true, tier: 1,
      commonName: "Sunflower",            sci: "Helianthus annuus",
      funFact: "Each sunflower 'head' is actually a composite of up to 2,000 tiny individual flowers.",
      image: "sunflower", emoji: "🌻" },

    // Invertebrate animals
    { id: "sponge",      parent: "porifera",         age_mya: 0, isLeaf: true, tier: 1,
      commonName: "Sea sponge",           sci: "Spongilla lacustris",
      funFact: "Has no neurons, muscles, or organs — yet can sneeze to clear its pores, taking about 30 minutes.",
      image: "sponge", emoji: "🧽" },
    { id: "jellyfish",   parent: "cnidaria",         age_mya: 0, isLeaf: true, tier: 1,
      commonName: "Moon jellyfish",       sci: "Aurelia aurita",
      funFact: "Has no brain, heart, or blood, yet coordinates complex swimming with a diffuse nerve net.",
      image: "moon-jellyfish", emoji: "🪼" },
    { id: "earthworm",   parent: "annelida",         age_mya: 0, isLeaf: true, tier: 2,
      commonName: "Earthworm",            sci: "Lumbricus terrestris",
      funFact: "Darwin spent 40 years studying earthworms; a single acre of soil can hold over a million of them.",
      image: "earthworm", emoji: "🪱" },
    { id: "octopus",     parent: "mollusca",         age_mya: 0, isLeaf: true, tier: 5,
      commonName: "Common octopus",       sci: "Octopus vulgaris",
      funFact: "Has three hearts, blue blood, and distributed intelligence — two-thirds of its neurons are in its arms.",
      image: "common-octopus", emoji: "🐙" },
    { id: "garden-snail", parent: "mollusca",        age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Garden snail",         sci: "Cornu aspersum",
      funFact: "Its slime is simultaneously a lubricant, adhesive, and structural material — strong enough to let it crawl upside-down or across a razor blade unharmed.",
      image: "garden-snail", emoji: "🐌" },
    { id: "velvet-worm", parent: "ecdysozoa",        age_mya: 0, isLeaf: true, tier: 7,
      commonName: "Velvet worm",          sci: "Peripatus juliformis",
      funFact: "A 'living fossil' nearly unchanged for 500 million years; hunts by spraying a sticky slime net from a distance.",
      image: "velvet-worm", emoji: "🐛" },
    { id: "starfish",    parent: "echinodermata",    age_mya: 0, isLeaf: true, tier: 3,
      commonName: "Common starfish",      sci: "Asterias rubens",
      funFact: "Has no brain — just a ring of nerves — yet can regenerate an entire limb from a single severed arm.",
      image: "starfish", emoji: "⭐" },
    { id: "barnacle",    parent: "crustacea",        age_mya: 0, isLeaf: true, tier: 7,
      commonName: "Acorn barnacle",       sci: "Semibalanus balanoides",
      funFact: "Darwin spent eight years studying barnacles; these sessile crustaceans cement themselves headfirst to rocks and kick food into their mouths with feathery legs.",
      image: "acorn-barnacle", emoji: "🐚" },
    { id: "sea-squirt",  parent: "tunicata",         age_mya: 0, isLeaf: true, tier: 6,
      commonName: "Sea squirt",           sci: "Ciona intestinalis",
      funFact: "Starts life as a free-swimming tadpole-like larva with a notochord, then metamorphoses into a sessile filter feeder.",
      image: "sea-squirt", emoji: "🌊" },
    { id: "spider",      parent: "arachnida",        age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Garden spider",        sci: "Araneus diadematus",
      funFact: "Silk is stronger than steel by weight; some spiders recycle it by eating their webs each morning.",
      image: "garden-spider", emoji: "🕷️" },
    { id: "horseshoecrab", parent: "chelicerata",    age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Horseshoe crab",       sci: "Limulus polyphemus",
      funFact: "Has survived largely unchanged for over 300 million years; its blue blood, which clots instantly around bacterial contamination, is used to safety-test every injectable medication.",
      image: "horseshoe-crab", emoji: "🦀" },
    { id: "fruitfly",    parent: "panorpida",        age_mya: 0, isLeaf: true, tier: 1,
      commonName: "Fruit fly",            sci: "Drosophila melanogaster",
      funFact: "The workhorse of genetics for over a century — it shares about 60% of its genes with humans.",
      image: "fruit-fly", emoji: "🪰" },
    { id: "honeybee",    parent: "holometabola",     age_mya: 0, isLeaf: true, tier: 1,
      commonName: "Honeybee",             sci: "Apis mellifera",
      funFact: "Communicates the precise direction and distance of flowers with a 'waggle dance'.",
      image: "honeybee", emoji: "🐝" },
    { id: "monarch",     parent: "panorpida",        age_mya: 0, isLeaf: true, tier: 3,
      commonName: "Monarch butterfly",    sci: "Danaus plexippus",
      funFact: "Migrates up to 4,800 km from Canada to central Mexico — yet no individual completes the round trip; the journey spans several generations.",
      image: "monarch-butterfly", emoji: "🦋" },
    { id: "aphid",       parent: "paraneoptera",     age_mya: 0, isLeaf: true, tier: 5,
      commonName: "Pea aphid",            sci: "Acyrthosiphon pisum",
      funFact: "Can reproduce parthenogenetically in summer, giving birth to live daughters already pregnant with their own daughters — three generations developing simultaneously.",
      image: "aphid", emoji: "🐛" },

    // Fish
    { id: "shark",       parent: "chondrichthyes",   age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Great white shark",    sci: "Carcharodon carcharias",
      funFact: "Sharks first appeared over 450 million years ago — more than 200 million years before the first dinosaurs — making them one of the oldest surviving vertebrate lineages on Earth.",
      image: "great-white-shark", emoji: "🦈" },
    { id: "zebrafish",   parent: "actinopterygii",   age_mya: 0, isLeaf: true, tier: 5,
      commonName: "Zebrafish",            sci: "Danio rerio",
      funFact: "Can fully regenerate a damaged heart — a property scientists are trying to replicate in humans.",
      image: "zebrafish", emoji: "🐟" },
    { id: "lungfish",    parent: "rhipidistia",      age_mya: 0, isLeaf: true, tier: 5,
      commonName: "African lungfish",     sci: "Protopterus annectens",
      funFact: "Breathes air with lungs and can survive droughts for up to four years encased in a dried mucus cocoon underground, its metabolism slowing to near zero.",
      image: "lungfish", emoji: "🐟" },
    { id: "coelacanth",  parent: "sarcopterygii",    age_mya: 0, isLeaf: true, tier: 8,
      commonName: "Coelacanth",           sci: "Latimeria chalumnae",
      funFact: "Thought extinct for 65 million years until a live specimen was caught in 1938; gives birth to live young.",
      image: "coelacanth", emoji: "🐠" },

    // Amphibians
    { id: "frog",        parent: "amphibia_clade",   age_mya: 0, isLeaf: true, tier: 5,
      commonName: "African clawed frog",  sci: "Xenopus laevis",
      funFact: "Was used as a live pregnancy test in the 1940s–60s: pregnant women's urine induced egg-laying.",
      image: "African-clawed-frog", emoji: "🐸" },
    { id: "axolotl",     parent: "amphibia_clade",   age_mya: 0, isLeaf: true, tier: 6,
      commonName: "Axolotl",              sci: "Ambystoma mexicanum",
      funFact: "Retains its larval features for life (neoteny) and can regenerate entire limbs, heart tissue, and parts of its brain.",
      image: "axolotl", emoji: "🦎" },

    // Reptiles
    { id: "komodo",      parent: "toxicofera",       age_mya: 0, isLeaf: true, tier: 6,
      commonName: "Komodo dragon",        sci: "Varanus komodoensis",
      funFact: "The world's largest lizard; females can reproduce without males in a process called parthenogenesis.",
      image: "komodo-dragon", emoji: "🦎" },
    { id: "boa",         parent: "serpentes",        age_mya: 0, isLeaf: true, tier: 3,
      commonName: "Boa constrictor",       sci: "Boa constrictor",
      funFact: "Kills by constriction — tightening its coils with each exhale until the prey's heart stops. Unlike most large snakes, boas give birth to live young rather than laying eggs, and retain tiny vestigial pelvic bones that males use as spurs during courtship.",
      image: "boa", emoji: "🐍" },
    { id: "mourning-gecko", parent: "gekkota",       age_mya: 0, isLeaf: true, tier: 5,
      commonName: "Mourning gecko",        sci: "Lepidodactylus lugubris",
      funFact: "Nearly all individuals are female and reproduce by parthenogenesis — cloning without fertilisation. Genetic analysis shows that each asexual lineage originated from a rare hybridisation between two sexually reproducing gecko species, making it one of the most geographically widespread reptiles in the Pacific.",
      image: "mourning-gecko", emoji: "🦎" },
    { id: "tuatara",     parent: "lepidosauria",     age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Tuatara",              sci: "Sphenodon punctatus",
      funFact: "Has a light-sensing 'third eye' on top of its skull and remains active at temperatures as low as 7 °C — colder than any other reptile; individuals have been known to live past 100 years.",
      image: "tuatara", emoji: "🦎" },
    { id: "turtle",      parent: "archelosauria",    age_mya: 0, isLeaf: true, tier: 1,
      commonName: "Green sea turtle",     sci: "Chelonia mydas",
      funFact: "Navigates thousands of kilometres using Earth's magnetic field to return to the exact beach where it hatched, decades later.",
      image: "green-sea-turtle", emoji: "🐢" },
    { id: "crocodile",   parent: "crocodilia",       age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Nile crocodile",       sci: "Crocodylus niloticus",
      funFact: "Africa's largest freshwater predator; it can bite with enough force to crush bone, yet its jaw-opening muscles are so weak its mouth can be held shut by hand.",
      image: "Nile-crocodile", emoji: "🐊" },

    // Extinct dinosaurs & pterosaurs
    { id: "triceratops", parent: "dinosauria",       age_mya: 0, isLeaf: true, tier: 7,
      commonName: "Triceratops",          sci: "Triceratops horridus",
      funFact: "Its skull — up to 2.5 m long — is one of the largest of any land animal ever, yet it was a plant-eater.",
      image: "triceratops", emoji: "🦕" },
    { id: "tyrannosaur", parent: "saurischia",       age_mya: 0, isLeaf: true, tier: 8,
      commonName: "Tyrannosaurus rex",    sci: "Tyrannosaurus rex",
      funFact: "Had the strongest bite force of any known land animal (~3,600 kg) and binocular vision as wide as a modern hawk's — more consistent with an active predator than a scavenger.",
      image: "tyrannosaur", emoji: "🦖" },
    { id: "pterosaur",   parent: "ornithodira",      age_mya: 0, isLeaf: true, tier: 8,
      commonName: "Pteranodon",           sci: "Pteranodon longiceps",
      funFact: "The first vertebrates to evolve powered flight, roughly 80 million years before birds; Pteranodon's wingspan reached up to 6 metres, yet its hollow bones kept it light enough to soar for days.",
      image: "pterosaur", emoji: "🦅" },

    // Birds
    { id: "pigeon",      parent: "inopinaves",       age_mya: 0, isLeaf: true, tier: 2,
      commonName: "Rock pigeon",          sci: "Columba livia",
      funFact: "The ancestor of all domestic pigeons; can navigate home from hundreds of kilometres away using magnetic fields and smell.",
      image: "pigeon", emoji: "🐦" },
    { id: "eagle",       parent: "inopinaves",       age_mya: 0, isLeaf: true, tier: 3,
      commonName: "Bald eagle",           sci: "Haliaeetus leucocephalus",
      funFact: "Can spot a rabbit from 3 km away; its nest can weigh over a ton after years of additions.",
      image: "bald-eagle", emoji: "🦅" },
    { id: "falcon",      parent: "australaves",      age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Peregrine falcon",     sci: "Falco peregrinus",
      funFact: "The fastest animal on Earth, reaching over 380 km/h in a dive; once nearly extinct from DDT-induced eggshell thinning, it is now one of conservation's greatest comeback stories.",
      image: "peregrine-falcon", emoji: "🦅" },
    { id: "parakeet",    parent: "australaves",      age_mya: 0, isLeaf: true, tier: 2,
      commonName: "Common parakeet",      sci: "Melopsittacus undulatus",
      funFact: "Also called the budgerigar; a budgerigar named Puck holds the Guinness record for bird vocabulary, with 1,728 words.",
      image: "parakeet", emoji: "🦜" },

    // Mammals
    { id: "platypus",    parent: "monotremata",      age_mya: 0, isLeaf: true, tier: 6,
      commonName: "Platypus",             sci: "Ornithorhynchus anatinus",
      funFact: "One of the only egg-laying mammals; males have venomous spurs on their hind legs and can sense electric fields with their bill.",
      image: "platypus", emoji: "🦆" },
    { id: "kangaroo",    parent: "marsupialia",      age_mya: 0, isLeaf: true, tier: 5,
      commonName: "Red kangaroo",         sci: "Macropus rufus",
      funFact: "Australia's largest native land animal; a joey is the size of a jellybean at birth and continues developing in the pouch.",
      image: "red-kangaroo", emoji: "🦘" },
    { id: "opossum",     parent: "marsupialia",      age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Virginia opossum",     sci: "Didelphis virginiana",
      funFact: "North America's only marsupial; 'playing possum' is an involuntary catatonic response to threat, not a conscious act.",
      image: "virginia-opossum", emoji: "🐀" },
    { id: "whale",       parent: "mysticeti",        age_mya: 0, isLeaf: true, tier: 3,
      commonName: "Blue whale",           sci: "Balaenoptera musculus",
      funFact: "The largest animal ever known to exist; its heart is the size of a small car.",
      image: "blue-whale", emoji: "🐋" },
    { id: "narwhal",     parent: "odontoceti",       age_mya: 0, isLeaf: true, tier: 3,
      commonName: "Narwhal",              sci: "Monodon monoceros",
      funFact: "The long tusk is a canine tooth that spirals through the upper lip; it contains millions of nerve endings used to sense pressure, temperature, and salinity.",
      image: "narwhal", emoji: "🦄" },
    { id: "bottlenose-dolphin", parent: "odontoceti",   age_mya: 0, isLeaf: true, tier: 2,
      commonName: "Bottlenose dolphin",   sci: "Tursiops truncatus",
      funFact: "Every individual develops a unique 'signature whistle' that functions as a name — other dolphins use it to address them specifically. Some populations in Shark Bay, Australia, carry marine sponges on their snouts while foraging, one of the most sophisticated tool-use behaviours recorded outside primates.",
      image: "bottlenose-dolphin", emoji: "🐬" },
    { id: "hippo",       parent: "whippomorpha",     age_mya: 0, isLeaf: true, tier: 3,
      commonName: "Hippopotamus",         sci: "Hippopotamus amphibius",
      funFact: "Secretes a red-orange fluid from its skin that acts as a natural sunscreen and antibiotic — long mistaken by observers for sweating blood.",
      image: "hippo", emoji: "🦛" },
    { id: "giraffe",     parent: "ruminantia",       age_mya: 0, isLeaf: true, tier: 1,
      commonName: "Giraffe",              sci: "Giraffa camelopardalis",
      funFact: "Has the same number of neck vertebrae as a human (7); its heart must pump blood 2 metres up to reach its brain.",
      image: "giraffe", emoji: "🦒" },
    { id: "pronghorn",   parent: "ruminantia",       age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Pronghorn",            sci: "Antilocapra americana",
      funFact: "The fastest land animal in the Western Hemisphere, capable of sustaining 90 km/h — likely evolved to outrun extinct American cheetahs.",
      image: "pronghorn", emoji: "🦌" },
    { id: "bactrian-camel", parent: "camelidae",     age_mya: 0, isLeaf: true, tier: 3,
      commonName: "Bactrian camel",        sci: "Camelus bactrianus",
      funFact: "The two humps store fat — not water — as an energy reserve; a depleted hump goes limp and flops to one side. Wild Bactrian camels, critically endangered and genetically distinct from domestic stock, are so well adapted to extreme cold that they have been observed drinking water from frozen lakes.",
      image: "Bactrian-camel", emoji: "🐫" },
    { id: "llama",       parent: "new_world_camelids", age_mya: 0, isLeaf: true, tier: 2,
      commonName: "Llama",                 sci: "Lama glama",
      funFact: "Used as pack animals in the Andes for over 6,000 years, llamas can carry up to 30% of their body weight over steep mountain terrain. When overloaded or confronted, they defend themselves by spitting a projectile of fermented stomach contents that can reach three metres.",
      image: "llama", emoji: "🦙" },
    { id: "alpaca",      parent: "new_world_camelids", age_mya: 0, isLeaf: true, tier: 2,
      commonName: "Alpaca",                sci: "Vicugna pacos",
      funFact: "Domesticated from wild vicuñas in the Andes some 6,000 years ago, alpacas are bred almost entirely for their fibre — extraordinarily fine, lanolin-free, and hollow, making it both hypoallergenic and one of the warmest natural materials.",
      image: "alpaca", emoji: "🦙" },
    { id: "indian-rhino", parent: "perissodactyla",   age_mya: 0, isLeaf: true, tier: 3,
      commonName: "Indian rhinoceros",     sci: "Rhinoceros unicornis",
      funFact: "The only single-horned rhinoceros; its prominent skin folds give it an armour-plated look but the skin is only 1–5 cm thick. Hunted to fewer than 200 individuals in the early twentieth century, its population has since recovered to over 4,000 — one of conservation's greatest comebacks.",
      image: "Indian-rhino", emoji: "🦏" },
    { id: "pangolin",    parent: "ferae",            age_mya: 0, isLeaf: true, tier: 6,
      commonName: "Pangolin",             sci: "Manis temminckii",
      funFact: "The world's most trafficked mammal; its scales are made of keratin — the same material as human fingernails.",
      image: "pangolin", emoji: "🐾" },
    { id: "cat",         parent: "felidae",          age_mya: 0, isLeaf: true, tier: 1,
      commonName: "Domestic cat",         sci: "Felis catus",
      funFact: "Technically still an apex predator — domestic cats kill an estimated 1–4 billion birds per year in the US alone.",
      image: "cat", emoji: "🐱" },
    { id: "lion",        parent: "felidae",          age_mya: 0, isLeaf: true, tier: 2,
      commonName: "Lion",                 sci: "Panthera leo",
      funFact: "The only truly social cat, living in prides of up to 30; lionesses do most of the hunting while males primarily defend territory.",
      image: "lion", emoji: "🦁" },
    { id: "spottedhyena", parent: "hyaenidae",       age_mya: 0, isLeaf: true, tier: 5,
      commonName: "Spotted hyena",        sci: "Crocuta crocuta",
      funFact: "Known for a complex matriarchal social structure and a vocalization that sounds like human laughter.",
      image: "spotted-hyena", emoji: "🐆" },
    { id: "aardwolf",    parent: "hyaenidae",        age_mya: 0, isLeaf: true, tier: 7,
      commonName: "Aardwolf",             sci: "Proteles cristata",
      funFact: "A specialized insectivore that can consume up to 300,000 termites in a single night using its long, sticky tongue.",
      image: "aardwolf", emoji: "🐺" },
    { id: "dog",         parent: "canis",            age_mya: 0, isLeaf: true, tier: 1,
      commonName: "Domestic dog",         sci: "Canis lupus familiaris",
      funFact: "Domesticated from wolves at least 15,000 years ago — the first species humans ever domesticated.",
      image: "dog", emoji: "🐶" },
    { id: "grey-wolf",   parent: "canis",            age_mya: 0, isLeaf: true, tier: 2,
      commonName: "Grey wolf",            sci: "Canis lupus",
      funFact: "Can travel over 200 km in a single day; its howl carries up to 10 km and coordinates the pack across vast territories.",
      image: "grey-wolf", emoji: "🐺" },
    { id: "red-fox",     parent: "canidae",          age_mya: 0, isLeaf: true, tier: 3,
      commonName: "Red fox",              sci: "Vulpes vulpes",
      funFact: "The most widely distributed wild carnivore on Earth, found from Arctic tundra to city suburbs across Europe, Asia, North America, and — through introduction — Australia.",
      image: "red-fox", emoji: "🦊" },
    { id: "panda",       parent: "arctoidea",        age_mya: 0, isLeaf: true, tier: 3,
      commonName: "Giant panda",          sci: "Ailuropoda melanoleuca",
      funFact: "Eats almost exclusively bamboo, yet is biologically classified as a carnivore; its apparent 'thumb' is an enlarged wrist bone, not a true digit.",
      image: "giant-panda", emoji: "🐼" },
    { id: "seal",        parent: "arctoidea",        age_mya: 0, isLeaf: true, tier: 6,
      commonName: "Harbor seal",         sci: "Phoca vitulina",
      funFact: "Can slow its heartbeat to just 4 beats per minute while diving and stay underwater for over 30 minutes.",
      image: "harbor-seal", emoji: "🦭" },
    { id: "giant-anteater", parent: "xenarthra",     age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Giant anteater",       sci: "Myrmecophaga tridactyla",
      funFact: "Has no teeth at all; its tongue flicks in and out 150 times per minute to lap up 35,000 ants and termites per day.",
      image: "giant-anteater", emoji: "🐜" },
    { id: "sloth",       parent: "xenarthra",        age_mya: 0, isLeaf: true, tier: 3,
      commonName: "Brown-throated three-toed sloth", sci: "Bradypus variegatus",
      funFact: "So sedentary that algae colonise grooves in its fur hairs, turning the coat greenish for camouflage. Unlike virtually all other mammals — which have exactly seven neck vertebrae — it has nine, allowing a 270° head rotation. Moths that live permanently in its fur lay their eggs in the sloth's weekly dung deposit.",
      image: "brown-throated-three-toed-sloth", emoji: "🦥" },
    { id: "elephant",    parent: "proboscidea",      age_mya: 0, isLeaf: true, tier: 1,
      commonName: "African bush elephant", sci: "Loxodonta africana",
      funFact: "The largest land animal alive; uses infrasound calls below human hearing to communicate over kilometres.",
      image: "African-elephant", emoji: "🐘" },
    { id: "manatee",     parent: "sirenia",          age_mya: 0, isLeaf: true, tier: 4,
      commonName: "West Indian manatee",   sci: "Trichechus manatus",
      funFact: "Shares its nearest land-living relatives with the elephant — both are afrotherians. Like elephants, manatees replace worn molars in a unique horizontal march: new teeth push forward from the back of the jaw, gradually expelling the old ones at the front, a system found in only these two mammal groups.",
      image: "West-Indian-manatee", emoji: "🌊" },
    { id: "elephant-shrew", parent: "afrotheria",    age_mya: 0, isLeaf: true, tier: 6,
      commonName: "Elephant shrew",       sci: "Elephantulus sp.", wiki: "Elephant shrew",
      funFact: "Despite weighing as little as 50 g, can sprint at nearly 30 km/h; it maintains a network of private escape trails through leaf litter, which it patrols and sweeps clear of debris each day.",
      image: "elephant-shrew", emoji: "🐭" },
    { id: "human",       parent: "hominidae",        age_mya: 0, isLeaf: true, tier: 3,
      commonName: "Human",                sci: "Homo sapiens",
      funFact: "The only species known to cook food, which may have driven the dramatic expansion of the brain.",
      image: "human", emoji: "🧑" },
    { id: "chimp",       parent: "hominidae",        age_mya: 0, isLeaf: true, tier: 1,
      commonName: "Chimpanzee",           sci: "Pan troglodytes",
      funFact: "Shares ~98.7% of DNA with humans; makes and uses tools, and has been observed in warfare between groups.",
      image: "chimp", emoji: "🐒" },
    { id: "mouse",       parent: "muridae",          age_mya: 0, isLeaf: true, tier: 1,
      commonName: "House mouse",          sci: "Mus musculus",
      funFact: "Shares ~85% of protein-coding genes with humans, making it an indispensable model for medicine.",
      image: "mouse", emoji: "🐭" },
    { id: "rat",         parent: "muridae",          age_mya: 0, isLeaf: true, tier: 2,
      commonName: "Brown rat",            sci: "Rattus norvegicus",
      funFact: "Laughs at ultrasonic frequencies when tickled, and can be trained to sniff out tuberculosis and landmines.",
      image: "rat", emoji: "🐀" },
    { id: "hamster",     parent: "rodentia",         age_mya: 0, isLeaf: true, tier: 4,
      commonName: "Syrian hamster",       sci: "Mesocricetus auratus",
      funFact: "Can store food in cheek pouches that stretch back to their hips; wild hamsters run up to 9 km a night.",
      image: "Syrian-hamster", emoji: "🐹" },
    { id: "rabbit",      parent: "glires",           age_mya: 0, isLeaf: true, tier: 2,
      commonName: "Domesticated rabbit",  sci: "Oryctolagus cuniculus",
      funFact: "Rabbits eat their own droppings once to extract extra nutrients — a process called cecotrophy.",
      image: "rabbit", emoji: "🐰" },
  ]
};

// Allow loading in Node.js (for checks/ and tests/)
if (typeof module !== 'undefined') module.exports = phylogeny;
